### ISSUE TITLE
Didn't find any result

### ISSUE THREAD

**Issue by dulfox** [pwernicki/timeshift-autosnap-dnf#1]
I have a rpi 4 with Fedora 37 (python3.11).

```
python3
Python 3.11.0rc1 (main, Aug  9 2022, 00:00:00) [GCC 12.1.1 20220628 (Red Hat 12.1.1-3)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sysconfig
>>> sysconfig.get_paths()
{'stdlib': '/usr/lib64/python3.11', 'platstdlib': '/usr/local/lib64/python3.11', 'purelib': '/usr/local/lib/python3.11/site-packages', 'platlib': '/usr/local/lib64/python3.11/site-packages', 'include': '/usr/include/python3.11', 'platinclude': '/usr/include/python3.11', 'scripts': '/usr/local/bin', 'data': '/usr/local'}
```

I've installed timeshift which is working.

```
sudo btrfs subvolume list /
ID 256 gen 1558 top level 5 path @home
ID 257 gen 1560 top level 5 path @
ID 258 gen 1490 top level 257 path var/lib/portables
ID 259 gen 1490 top level 257 path var/lib/machines
ID 260 gen 1498 top level 5 path timeshift-btrfs/snapshots/2022-08-21_23-53-01/@
ID 261 gen 1499 top level 5 path timeshift-btrfs/snapshots/2022-08-21_23-53-01/@home
```

I was looking for automatic snapshots from dnf actions.
I've heard that timeshit-autosnap-dnf did the trick but it doesn't seem to work.
I've saw timeshift-autosnap-apt which is based on timeshift-autosnap from AUR and both have more than only a python file.

BTW, the directory given from getting the path from "purelib" returns a non existing one: 
`/usr/local/lib/python3.11/site-packages`
To be sure, I've created it.
I have make the python script executable and create links to different places where it could be located but it still doesn't work.

**Could you please provide more explanations on how it should work ?**

**Comment by pwernicki** [comment]
Please provide output of this command:
`timeshift --list`

**Comment by dulfox** [comment]
$ sudo timeshift --list

```
/dev/sda3 is mounted at: /run/timeshift/backup, options: rw,seclabel,relatime,compress=zstd:1,space_cache=v2,subvolid=5,subvol=/

Device : /dev/sda3
UUID   : 050536bd-2ab3-470e-b0d0-d851db3565f6
Path   : /run/timeshift/backup
Mode   : BTRFS
Status : OK
1 snapshots, 56.9 GB free

Num     Name                 Tags  Description
------------------------------------------------------------------------------
0    >  2022-08-21_23-53-01  O

```

**Comment by pwernicki** [comment]
You should use /usr/lib/python3.11/site-packages/dnf-plugins directory
For some reason python returns different purelib directory.
Put timeshiht.py to directory i wrote and everytime you run dnf this plugin make snapshot for you.

**Comment by dulfox** [comment]
I've created a link to that location and I can see it's called but I have this following error each time I invoke dnf:

```
Traceback (most recent call last):
  File "/usr/bin/dnf", line 62, in <module>
    main.user_main(sys.argv[1:], exit_code=True)
  File "/usr/lib/python3.11/site-packages/dnf/cli/main.py", line 201, in user_main
    errcode = main(args)
              ^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/dnf/cli/main.py", line 67, in main
    return _main(base, args, cli_class, option_parser_class)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/dnf/cli/main.py", line 102, in _main
    cli.configure(list(map(ucd, args)), option_parser())
  File "/usr/lib/python3.11/site-packages/dnf/cli/cli.py", line 832, in configure
    self.base.init_plugins(opts.disableplugin, opts.enableplugin, self)
  File "/usr/lib/python3.11/site-packages/dnf/base.py", line 308, in init_plugins
    self._plugins._run_init(self, cli)
  File "/usr/lib/python3.11/site-packages/dnf/plugin.py", line 151, in _run_init
    plugin = p_cls(base, cli)
             ^^^^^^^^^^^^^^^^
TypeError: Timeshift.__init__() takes 2 positional arguments but 3 were given
```

**Comment by pwernicki** [comment]
This script was tested on Fedora 35/36. I must install fedora 37 to debug this. Maybe dnf plugins work different on newer versions.

**Comment by pwernicki** [comment]
OK, i add cli to init and now it should work as expected. Please pull new changes from repo.

**Comment by dulfox** [comment]
Sorry for the delay.
I've updated the script.
Edit : It works

timeshift --list

```
/dev/sda3 is mounted at: /run/timeshift/backup, options: rw,seclabel,relatime,compress=zstd:1,space_cache=v2,subvolid=5,subvol=/

Device : /dev/sda3
UUID   : 050536bd-2ab3-470e-b0d0-d851db3565f6
Path   : /run/timeshift/backup
Mode   : BTRFS
Status : OK
6 snapshots, 52.4 GB free

Num     Name                 Tags  Description                        
------------------------------------------------------------------------------
0    >  2022-08-21_23-53-01  O                                        
1    >  2022-08-26_09-00-02  D                                        
2    >  2022-08-26_23-50-36  O                                        
3    >  2022-09-03_22-26-30  O                                        
4    >  2022-09-03_22-56-40  O     before dnf install sha1sig-tracer  
5    >  2022-09-03_23-00-01  O     after dnf install sha1sig-tracer
```
